name: DimensionDoor
main: name.richardson.james.dimensiondoor.DimensionDoor
version: 1.7.0
author: James Richardson (grandwazir)
description: Multiworld management made easy.
website: https://github.com/grandwazir/DimensionDoor 
database: true
commands:
  "dd":
    description: 'Main command for dimension door'
    usage: '/dd [create|teleport|unload|remove|modify|info|list|load|spawn|template]'