name: DimensionDoor
main: name.richardson.james.bukkit.dimensiondoor.DimensionDoor
version: ${project.version}
author: James Richardson (grandwazir)
description: Multiworld management made easy.
website: https://github.com/grandwazir/DimensionDoor 
commands:
  "dd":
    description: 'Main command for dimension door'
    usage: '/dd [create|teleport|unload|remove|modify|info|list|load|spawn|template]'
