name: DimensionDoor
main: name.richardson.james.dimensiondoor.DimensionDoorPlugin
version: 1.0.0
database: true
commands:
  dd:
    description: 'Main command for dimension door'
    usage: '/dd [create]'